### ISSUE TITLE
Проблем след deploy in Heroku

### ISSUE THREAD

**Issue by DesislavaGetova-Petrova** [luchob/softuni-heroku-test#1]
Здравей Лъчо, след 

       [INFO] BUILD SUCCESS
       [INFO] ------------------------------------------------------------------------
       [INFO] Total time:  25.879 s
       [INFO] Finished at: 2021-04-04T16:08:12Z
       [INFO] ------------------------------------------------------------------------
-----> Discovering process types
       Procfile declares types -> web
-----> Compressing...
       Done: 189.1M
-----> Launching...
       Released v5
       https://doma6noto.herokuapp.com/ deployed to Heroku

се опитах да видя приложението но даде грешка:

Аpplication error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command heroku logs --tail

Би ли ме посъветвал какво да направя? https://github.com/DesislavaGetova-Petrova/demo

**Comment by luchob** [comment]
Привет!

Ммм... необходимо е да видиш логовете на апп-а, иначе няма да стане нищо. Това става с инсталиране на heroku CLI. После от команден ред трябва да се логнеш, ако не ме лъже паметта става така:

`heroku login`

После, за да видиш логовете:

heroku logs --tail -app <the_name_of_your_app>

Поздрави,
Л.

**Comment by DesislavaGetova-Petrova** [comment]
Благодаря! Успешна нова седмица!

**Comment by DesislavaGetova-Petrova** [comment]
Здравей отново,
разбрах че проблема ми е в .jar файла "Unable to access jarfile /target/demo.jar", но не успях да го оправя. A като стартирам самия demo.jar ми дава "no main manifest attribute, in C:\Users\desy_\Desktop\heroku-test\target\demo.jar". Четох в нета,  добавих някои неща в .pom, но все същото. Моля, ако може за малко помощ.

**Comment by luchob** [comment]
Здравей, Деси! 

Два въпроса... 
1. Става въпрос за деплоймънта в хероку ли?
2. В слайдовете е записано в Procfile да бъде:

```
web: java -jar target/name-version.jar
```

При теб, обаче започва с / 
```
web: java -jar /target/demo.jar
```

Пробва ли го? За съжаление в момента не съм в нас и не може да погледна тези неща, но отговорите ще са от полза :-)

Л.

**Comment by luchob** [comment]
И да добавя - demo.jar не трябва да е комитнато в github :-)

**Comment by DesislavaGetova-Petrova** [comment]
Ясно, ще пробвам и ще пиша, благодаря!

**Comment by DesislavaGetova-Petrova** [comment]
За съжаление и след направените промени дава същата грешка. По въпросите: 
1. Да 
2. Да, промених да бъде web: java -jar target/demo.jar. Махнах и demo.jar от github .
Понеже не е спешно или належащо, аз за днес сигурно няма да мога да направя повече проби, Благодаря за бързите отговори и извинявай за безпокойството! Лека вечер!

**Comment by luchob** [comment]
Здравей!

Тъй като имаш версия в pom.xml името на jar file-a, който се генерира и който описваш в Procfile съдържа тази версия. Ето, следващия скрийншот, след един `mvn clean package`:

<img width="784" alt="Screenshot 2021-04-05 at 21 45 24" src="https://user-images.githubusercontent.com/10339738/113612773-ed73a680-9658-11eb-91f5-2756a2869c5d.png">

В Procfile името трябва да е същото. Опитай да видим :-)

Л.

**Comment by DesislavaGetova-Petrova** [comment]
Здравей, след добавяне на версията в Procfile и поправка  port: ${PORT:8000} защото го бях писала само port: 8000 в application.yml, вече не се сърди за .jar файла, 
но сега дава 
"Exception in thread "main" java.lang.NoClassDefFoundError: at.........ProjectAplication.java
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.SpringApplication
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoadeer.java:606)
at java.base/jdk.internal.loaderClassLoader$AppClassLoader.loadClass(ClassLoadeer.java:168)
at java.base/java.lang.ClassLoader.loadClass(ClassLoadeer.java:522)
Какво отново не е както трябва ?

**Comment by luchob** [comment]
Е, виж, че има напредък :-)

В proc file-a трябва да има изпълнимия uber-jar, т.е.:
```
web: java -jar target/demo-1.0.0-SNAPSHOT-exec.jar
```

Освен това, се сещам къде би могъл да е следващия проблем. Трябва да добавиш CLOUDINARY_SECRET environment variable. В твоя хероку апп, цъкни Settings, после ако не се лъжа бяха Config Vars.

Нека видим какво ще гръмне след това :P

**Comment by DesislavaGetova-Petrova** [comment]
Да, напредък има и след добавяне на изпълнимия .jar.  CLOUDINARY_SECRET environment variable бях добавила преди това, както показа на лекцията. Сега се стигна дори до:

Tomcat started on port: 16061(http)...
Started ProjectApplication in 10.955 sec (JVM)...

и след това ConditionEvaluetionReportLoggingListener:

Error starting ApplicationContext:..........................
java.lang.IligalStateExeption: Failed to execute CommandLineRunner
at org.springframework.boot.SpringApplication.callRunner
................................................................................................run
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Metod)...
Аз имам  в едно Repository @Query, това ли е проблема?

**Comment by DesislavaGetova-Petrova** [comment]
Не би трябвало да е това, защото и в проекта който успя да деплойнеш на лекцията също има @Query...

**Comment by DesislavaGetova-Petrova** [comment]
Сега допрочетох в грешките, че не харесва и SeedUnitNames, което е от един .json файл...
Моля да ме извиниш за досаждането ! Лека вечер!

**Comment by DesislavaGetova-Petrova** [comment]
Махнах сиидването и тръгна !!! Благодаря за всичко!!!

**Comment by luchob** [comment]
Супер :) успех на изпита и лека нощ :)
