### ISSUE TITLE
Heroku

### ISSUE THREAD

**Issue by ZBashev** [luchob/softuni-heroku-test#3]
Здравейте, гледам лекцията  правя каквото трябва, но не се получава . Деплойва  ,но не тръгва. Ще Ви изправя покана към моето репозитори , ако имате възможност да го погледнете.

Поздрави

**Comment by ZBashev** [comment]
-----> Building on the Heroku-20 stack
-----> Using buildpack: heroku/gradle
-----> Gradle app detected
-----> Spring Boot detected
-----> Installing JDK 11... done
-----> Building Gradle app...
-----> executing ./gradlew build -x check
       ./gradlew: 39: cd: can't cd to "./
       Downloading https://services.gradle.org/distributions/gradle-7.0.2-bin.zip
       ..........10%...........20%...........30%..........40%...........50%...........60%..........70%...........80%...........90%..........100%
       To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.0.2/userguide/gradle_daemon.html#sec:disabling_the_daemon.
       Daemon will be stopped at the end of the build 
       > Task :compileJava
       > Task :processResources
       > Task :classes
       > Task :bootJarMainClassName
       > Task :bootJar
       > Task :jar SKIPPED
       > Task :assemble
       > Task :build
       
       BUILD SUCCESSFUL in 58s
       4 actionable tasks: 4 executed
-----> Discovering process types
       Procfile declares types -> web
-----> Compressing...
       Done: 104.5M
-----> Launching...
       Released v8
       https://test-musikdb.herokuapp.com/ deployed to Heroku

**Comment by luchob** [comment]
За да се види какъв е проблемът, трябва да се видят логовете на приложението. От тези на деплоймънта не става ясно. Допускам, липсва някой env variable...

**Comment by ZBashev** [comment]
Благодаря
